version: '3.8'

##############
#
# https://sisnato.redebrasilrp.com.br/
#
#############

services:
  frontend:
    image: sys_nato_front_prod:1.3.6
    build:
      context: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 250M